#controllers:
#    resource: ../../src/Controller/
#    type: annotation

controllers:
    resource: ../../src/DrivaniaCandidate/Ports/Controller/
    type: annotation


kernel:
    resource: ../../src/Kernel.php
    type: annotation
